### ISSUE TITLE
Help me pls

### ISSUE THREAD

**Issue by andriy-as** [odedolive/RedditPurge#1]
hi, i'm just learning to program, can i contact you to talk? I found your article on the Internet how to log in to Facebook and make posts, and I would like to ask how you can like any post. Write me

**Comment by odedolive** [comment]
Hi, what can I do for you?
Probably not the best medium to chat, so I might delete it later... but what do you need?

**Comment by andriy-as** [comment]
don’t know English, I will write using google translate, you have done several lessons how to use C # and selenium to log in to facebook and make posts. I would like you to say how I could like to post on Facebook, the Like button has no id. I do not know how to work with xpath and selector.
thanks for writing to me

**Comment by andriy-as** [comment]
if you can write me an email andreyhka@gmail.com
